_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 15
                - 23
                - 55
            "4": 3.10.8
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: MNIST
epochs:
    value: 100
hidden_dims:
    value:
        - 256
        - 128
        - 64
kld_weight:
    value: 0.00025
latent_dim:
    value: 20
lr:
    value: 0.005
scheduler_gamma:
    value: 0.95
seed:
    value: 0
weight_decay:
    value: 0
