_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
            "2":
                - 1
                - 41
                - 51
                - 55
            "3":
                - 15
                - 23
                - 55
            "4": 3.10.8
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 128
channels:
    value: 1
dataset:
    value: mnist
device:
    value: cuda
epochs:
    value: 1000
hidden_size1:
    value: 256
hidden_size2:
    value: 512
hidden_size3:
    value: 1024
img_size:
    value: 28
lr:
    value: 0.0002
noise_size:
    value: 100
seed:
    value: 0
